service: marc-medics-backend
runtime: nodejs20

instance_class: F2

handlers:
- url: /*
  secure: always
  script: auto

env_variables:
  GAE_ENV: "standard"
  NODE_ENV: "production"
  PORT: 8080
  GOOGLE_APPLICATION_CREDENTIALS: "svc-acc-stg-fartech.json"